# Generated by Django 5.2.1 on 2025-06-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0003_rename_url_productimages_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='currency',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
