# Generated by Django 5.2.1 on 2025-06-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0005_rename_cartentries_cartentry_rename_orders_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
