# Generated by Django 5.2.1 on 2025-06-06 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_management', '0006_rename_pin_code_order_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders_management.order'),
        ),
        migrations.DeleteModel(
            name='ProductDiscountEntry',
        ),
    ]
